name: Sync Notion pages to posts

on:
  schedule:
    - cron: '0 20 * * *'
    
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate posts
        uses: bndynet/github-action-notion@v1
        with:
          notion-token: ${{ secrets.NOTION_TOKEN}}
          root-page-id: ${{ secrets.NOTION_ROOT_PAGE_ID }}

      - name: Commit posts
        uses: EndBug/add-and-commit@v9
        with:
          add: '_posts'
          message: Sync Notion pages to posts by GitHub Actions
          committer_name: joao
          committer_email: joaovitordinizmistrinel2003@gmail.com
